### ISSUE TITLE
the plugin doesnt work at all

### ISSUE THREAD

**Issue by starryskies2** [l2-/template-plugin#16]
hey, i was wondering if there is any issue with the plugin? today its just stopped working tried turning it off and on and it didnt change anything,normal xp drops works tho

**Comment by l2-** [comment]
Yesterday the plugin was updated to v1.3.3. with changes: `Show predicted hit when Hitpoints skill is filtered. Allow for larger default(Runescape) font size.`. As far as i can tell it works fine for me so it could be behavior due to your settings for this plugin? It's also possible the overlay falls outside of the game canvas for you.

**Comment by Jin-Jiyunsun** [comment]
related to this I think? Exp drop font is now somewhat garbled at certain font sizes for me? Font size 16 was fine but the number I usually have it on is garbled like in the image I've attached along with my settings.

![bugged xpdrops](https://user-images.githubusercontent.com/37377657/155896472-ab2b2256-a480-430c-ad4f-6ccb81508456.png)

**Comment by starryskies2** [comment]
thank you,i had an issue with the settings its working,bit different font but not big deal thanks alot!!
