### ISSUE TITLE
[FEATURE REQUEST] Support for colored max hits

### ISSUE THREAD

**Issue by blismatic** [l2-/template-plugin#24]
### Add an option for "Xp drop color max" underneath the "Xp drop color range" option.

With this option, whenever you hit your maximum hit in your currently equipped gear (offensive prayers such as piety and rigour included in calculation), the color of the xp drop would show up differently to quickly indicate to the player that they have gotten a max hit.

It's not much, but I have however included the code for how _I think_ the `XpDropsConfig.java` file would change. 
```java
@ConfigItem(
	keyName = "xpDropColorMax",
	name = "Xp drop color max",
	description = "Color of the XP drop text when hitting your max hit",
	position = 11,
	section = xp_drop_settings
)
default Color xpDropColorMax()
{
	return Color.WHITE;
}
```

Some special cases to consider would be things such as salve amulet against undead creatures, dragon hunter weapons against Vorkath, Olm, etc.. and some other niche cases probably exist im sure. I would try to implement this myself and send a push request, but I'm not sure how to calculate the max possible hit of someone's current gear.

**Comment by l2-** [comment]
The idea is cool but what used to be a simple customizable xp drop plugin is growing into a enormous plugin that does a lot of niche stuff so I'm not eager to work on this right now. `I would try to implement this myself and send a push request, but I'm not sure how to calculate the max possible hit of someone's current gear.`
Specifically, as you noted, the logic and implementation to know when you actually hit a max hit is large and complex. I'm sure it has been done before so it could be copied from there but this comes back to the point I was trying to make about the plugin becoming bloated. Another issue that personally annoys me but that I do not have a good fix for is that the predicted hit is plain wrong for many monsters in the game currently. Either because of party scaling or because the bundled xp modifiers are not complete/ up to date/ wrong and when the predicted hit is wrong it will for sure not match with the calculated max hit even if you did hit a max hit.

**Comment by blismatic** [comment]
Fair enough, I understand where you're coming from completely. Idea aside, great work on the plugin as it currently stands and thank you for taking the time to respond to me.

**Comment by wuudan** [comment]
> Fair enough, I understand where you're coming from completely. Idea aside, great work on the plugin as it currently stands and thank you for taking the time to respond to me.

Hey, I know this is probably not a good way to contact you but I was hoping you could give me your discord - I'm interested in your minecraft account "Dare"
