### ISSUE TITLE
customizable xp drop not attached to target.

### ISSUE THREAD

**Issue by lvl30ditto** [l2-/template-plugin#27]
right now its just floating around some where. yesterday iit was working fine. now its not working. its floating some where of screen. maybe the new update broke it

**Comment by TylerHarding** [comment]
This issue seems to only be happening with the attach to target / attach to player options. With those turned off, xp drops appear in the standard rendered drop area as expected.

**Comment by lvl30ditto** [comment]
gonna wait for the update :)

**Comment by l2-** [comment]
Hi, seems from a bit of testing that Runelite made it so the overlay now takes the moveable overlay position into account even for overlays that are of the dynamic type (or maybe its because I change the type to dynamic at runtime which might not be what the Runelite people expect someone to do). In any case a little workaround until this is fixed: turn OFF attack to player and attach to target. Hold alt and drag the overlay to the top left corner of the screen. Make sure it does not snap to the group in the top left or the position changes when another overlay in that group is rendered in front of this one. Now turn on either of the attach options again and the xp drops should be in the correct place again.

**Comment by l2-** [comment]
https://github.com/runelite/plugin-hub/pull/2705 This should fix it.

**Comment by lvl30ditto** [comment]
when will runelite update the version from 1.5 to 1.5.1

**Comment by ruchir90** [comment]
> when will runelite update the version from 1.5 to 1.5.1

dude relax it will come when its ready be grateful for the free service

**Comment by NarZook** [comment]
> > when will runelite update the version from 1.5 to 1.5.1
> 
> dude relax it will come when its ready be grateful for the free service

Dude just asked a question..

**Comment by l2-** [comment]
> when will runelite update the version from 1.5 to 1.5.1

There's a couple of people who can merge and one of those has to merge the pull request. All of them are volunteers so it's hard to say when they have time to do it.

That said 1.5.1 is now merged and should be live, hope it solves the issue.

**Comment by ruchir90** [comment]
> > > when will runelite update the version from 1.5 to 1.5.1
> > 
> > 
> > dude relax it will come when its ready be grateful for the free service
> 
> Dude just asked a question..

Dude relax go outside and touch grass instead of arguing to a convo you weren't even a part of.

**Comment by lvl30ditto** [comment]
> > > > when will runelite update the version from 1.5 to 1.5.1
> > > 
> > > 
> > > dude relax it will come when its ready be grateful for the free service
> > 
> > 
> > Dude just asked a question..
> 
> Dude relax go outside and touch grass instead of arguing to a convo you weren't even a part of.

can you not start shit? ur comment didnt add any value. i was just hyped for the plugin i just recently discovered. some one else defended me. and now ur trying to start drama. you should leave this. go outside and touch grass.

**Comment by lvl30ditto** [comment]
Thank you for everything l2- gonna close the ticket since everything is resolved :D
