### ISSUE TITLE
Feature Request: Change xp drop location based on attack style

### ISSUE THREAD

**Issue by Fiffers** [l2-/template-plugin#30]
When config.attachToTarget is true, the xp drops will be attached to the players target while in combat. I like to enable this setting because it subjectively feels like that's where the xp drops _should_ be displayed. However, I find it kind of strange to not have the xp drops not near the center of the screen when in ranged (not melee) combat.

I'd like to propose a similar setting that checks the selected attack style and uses that information to determine where to display the xp drop. If the player has a melee style selected, attach the drops to the target, otherwise attach it to the player.

I'd be happy to put in a PR for this myself but wanted to gauge opinions beforehand. Thanks for your input!

**Comment by l2-** [comment]
Personally I think this is too niche to dedicate more settings to in the config. I'm biased since I don't use attach to target or player myself. I imagine this would either be a toggle to attach to player for mage/range or a field for skill for which attach to is ignored. Basically I can't think of a way to add this that doesn't clutter the settings even more as there are already a lot of them. Maybe a simple toggle for keeping XP drops in the viewport at all times? Although that isn't exactly what you are requesting.

**Comment by Fiffers** [comment]
Yeah, fair enough. You're right, it is pretty niche. I'll close this issue.
