### ISSUE TITLE
Rapid attacks and predicted hits cause text overlap

### ISSUE THREAD

**Issue by CreativeTechGuy** [l2-/template-plugin#51]
![image](https://user-images.githubusercontent.com/12002072/208572165-d06cee3f-02aa-4ecf-af2a-f438d47df2c1.png)

This is with the following settings: (And using darts on rapid)

* Group XP Drops: false
* XP drop delay: 25
* Vertical XP drop speed: 25
* Time until disappear: 150
* Show predicted hit: true

I've played around with the timings of all relevant settings and I cannot find a good way to avoid this issue. When the hits are spaced out this is not an issue, only after 3+ consecutive hits do the numbers start severely overlapping as shown. It seems to be a specific issue with predicted hits as the XP drops don't overlap with each other, only the predicted hit and XP overlap with each other.

**Comment by l2-** [comment]
Ok the overlapping is indeed a bug with my implementation that I'm fixing however I want to clear something up on your chosen settings here. 

The numbers have a somewhat confusing unit of measurement. 1 unit is 1/50 of a second. 
For `XP drop delay: 25` that means if a previous xp drop would overlap with a new xp drop delay the new xp drop by up to 25 (so 0.5 seconds). Since there are 3 drops per hit and you fire a weapon every 2 server ticks (1 server tick is on average 0.6 seconds so 30 units) that means every 60 units 3 drops have to be processed. 
Using a delay of 25 means you drag this out to at most 75 units causing the drops to keep backing up further and further creating a delay in when you will see them. Right now the implementation has a bug causing overlaps instead of properly delaying. I'm fixing this so it no longer overlaps however doing so would introduce the issue I just described. With your settings you would effectively keep delaying xp drops making the xp drops and predicted hits feel unresponsive. You would need to set xp drops delay to at most **20** so 3 drops can be processed in 2 server ticks but as you would notice with your `Vertical XP drop speed: 25` setting this would cause overlap again. Calculating the minimum speed you would need for non overlapping xp drops is not as simple since it depends on the size of the xp drop which is also configurable however i found from testing that in your case a minimum speed of **30** works great.

I hope I cleared up this issue well enough. TLDR: Yes this is a bug currently but fixing it will reveal an issue with your chosen settings.

ps. I can't wait for people to find out I broke their setup because it was relying on this bugged behavior lol.

**Comment by CreativeTechGuy** [comment]
Thanks for explaining that. It sounds like a bad gotcha. Can the values be clamped based on the other values so that things like you describe cannot happen? So given the values I had in my example, the max delay value can be 20 and because I set it to 25, it'll get clamped down to 20. There's so many combinations here and yeah that's definitely some weird math, it'd be really nice if the plugin could lend a hand so people cannot make easy mistakes like this.

**Comment by CreativeTechGuy** [comment]
Actually, in thinking about this more, I think there's a better, more general solution to the drop backlog. Instead of trying to adjust the setting values, predictively, do it reactively. So once there's more than 3 drops in the queue, the speed of all of the drops starts increasing to relieve the backlog pressure.

I'm thinking something like this:
* drop delay starts at: 30
* one drop comes in every tick - no issue
* now 3 drops come in every tick - drops are now piling up in the queue
  * so the drop delay starts ticking down, let's say -5 per tick - after 1.2 seconds the drop delay will now be the correct value where there is no longer backlog pressure
* one drop comes in every tick again
  * the drop delay now starts increasing back to the actual setting value since the queue is never close to being full 

The actual numbers/details here can be adjusted based on the implementation, this could even behind a new boolean setting which is enabled by default. But the big benefit is that no matter what combination of settings and in-game actions, the plugin will always work to ensure that the drops don't start filling up a backlog.

**Comment by l2-** [comment]
I don't think I will do that. It makes the behavior of xp drops unpredictable for the end user as the plugin silently starts ignoring the speed setting whenever it thinks it needs to (or delay but then spacing would suffer which can cause overlap). I would much rather have the user notice their configuration is problematic and adjust it themselves. On top of that implementing what you're describing would lead to adding some real complex code for a very small user caused issue to an already over engineered code base. At the end of the day it's just a xp drop plugin that lets you tinker with the relevant parameters.

**Comment by CreativeTechGuy** [comment]
Okay. That makes sense. How will a user know that they need to adjust their timings? Currently the flexible timings with no feedback seems like a footgun since the only way you'd know they were broken is if you realize your hit spats are severely delayed. And every training method in the game requires a different set of options based on the number of skills you gain experience in and at what rate.

How would a user know:
1. That something needs to be changed
2. What exactly needs to be changed

**Comment by l2-** [comment]
1. Before the patch I submitted today -> overlapping xp drops
After the patch I submitted today -> constant stream of xp drops causes current xp drops to lag behind/be delayed.
2. Hard to say. The config description is already annoying in my opinion when more than 2 sentences so writing a book work there to make users aware of the way xp drops delay works is not a great option. Detecting when it goes wrong is possible by simply looking at severe delays but as said before even severe delays are sometimes valid (like an xp drop for all skills in 1 tick because of a quest or something) and even then I don't see how to bring it up to the user. Maybe a message in the in game chatbox but I'm not very fond of that idea either.

What I'm personally aiming for is for this plugin to be transparent and consistent. Let the user play around with the settings (of which there are so many I dread adding even more) and be guided by their intuition to configure the plugin to their liking. If the user ends up configuring the plugin in such a way that the experience degrades I personally rather have the user handle it themselves than fix it for them in the background. Although my opinion on this is also guided by the fact that I think it would be extremely annoying to catch degenerate cases without writing a bunch of super complex code that needs to be tested and maintained and god forbid affects the rest of the plugin.
