### ISSUE TITLE
Xp Drops Don't Center on Anchor

### ISSUE THREAD

**Issue by bheisenberg** [l2-/template-plugin#53]
Xp Drops sit to the left or right of the anchor they're hooked on based on the Horizontal direction field as opposed to centering, even if there's no horizontal movement.

**Examples:**
![image](https://user-images.githubusercontent.com/15053687/213267964-d89427ef-dcf0-4b21-b468-f2e8f5b65a97.png)
_Normal Xp drop (plugin disabled)_

![image](https://user-images.githubusercontent.com/15053687/213268054-af275a74-444d-4f26-befb-867a1f5c6866.png)
_Horizontal direction left (plugin enabled)_

![image](https://user-images.githubusercontent.com/15053687/213268180-9e4e2da7-e215-4cc8-85af-af8f9d55f396.png)
_Horizontal direction right (plugin enabled)_

Ideally, the xp drop should appear centered like when the plugin is off when there's no horizontal movement.

**Comment by l2-** [comment]
The plugin (or Runelite for that matter) has no concept for left, right or center anchoring. The horizontal direction affecting location is a by-effect of the approximation of the size of the xp drop as well as the anchoring position switching sides to keep the positioning of the xp drop intuitive. It wasn't really meant to determine the anchoring position either. `Ideally, the xp drop should appear centered like when the plugin is off when there's no horizontal movement.` doing this would be wrong too since it should only be the case when the user actually wants to be centered. For example the default position is top right without horizontal movement and it should not be centered in that case. I could change the settings (and break everyone's configuration for this plugin) and add centered to anchor positions but I don't really want to do that right now. You could try free position instead of anchored or attached to player instead.

**Comment by l2-** [comment]
Should be possible to configure once https://github.com/runelite/plugin-hub/pull/4950 is merged
