### ISSUE TITLE
Overlay going above xp globe overlay

### ISSUE THREAD

**Issue by Jbleezy** [l2-/template-plugin#63]
When both the xp globe overlay and the overlay from this plugin are locked to the same area, the overlay from this plugin is now going on top where before it didn't

**Comment by l2-** [comment]
It's because i set the priority explicitly now. There's a ton overlays that the plugin needs to account for and i don't think theres a perfect priority for the overlay in this plugin. Maybe i should change the layer back to above widgets to avoid most of the collision cases. Although under widgets is more logical I didn't see a real change in behavior so why did you pull request it to be under widgets?

**Comment by Rakqoi** [comment]
This is a problem for me as well. I like to have both xp drops and xp orbs in the corner beside my minimap, but now the xp drops appear above the orbs and it pushes orbs way down on the screen. It's a huge shame, since I really love this plugin, but I can't use it like this unfortunately. I hope you consider reverting the change, or change the ordering so it is forced to appear below xp orbs.
![2023-03-01_21-03-18](https://user-images.githubusercontent.com/31815644/222312251-c3b03cfa-0d47-4d99-a732-015877ab1919.png)

**Comment by Jbleezy** [comment]
> 

I think the xp globe overlay should definitely be accounted for though since these two overlays are very closely related. If that is possible while keeping under widgets that would be amazing.

**Comment by l2-** [comment]
Honestly I don't think I can do anything but set the xp globes overlay priority explicitly (because right now it's set to none which means sorting the overlays is done in first added first shown matter which is very inconsistent) and i really doubt runelite would bother or even want to accept that...

**Comment by l2-** [comment]
Should be possible to configure once https://github.com/runelite/plugin-hub/pull/4950 is merged
